#!/bin/bash

# if [ "$RELEASE_BRANCH" == "$SOURCE_BRANCH" ]; then
#   curl -X POST \
#        -F token=$BITCOIN_TESTNET_TOKEN \
#        -F ref=$SOURCE_BRANCH \
#        $BITCOIN_TESTNET_URL
# elif [ "$PATCHED_BRANCH" == "$SOURCE_BRANCH" ]; then
#   curl -X POST \
#        -F token=$BITCOIN_TESTNET_TOKEN \
#        -F ref=$BRANCH_TEST \
#        $BITCOIN_TESTNET_URL
# else
#   BRANCH=$(curl -s https://api.github.com/repos/bitcoin/bitcoin/tags | grep -i name | awk 'NR==1{print $2}' | tr -d "\",")
#   if [ -z "$BRANCH" ];then
#     echo "no branch could be found."
#     exit 1
#   fi
#   docker tag $IMAGE_NAME $DOCKER_REPO:$BRANCH
#   docker push $DOCKER_REPO:$BRANCH
# fi
MOST_RECENT_TAG=$(curl -s https://api.github.com/repos/lightningnetwork/lnd/tags | grep -i name | awk 'NR==1{print $2}' | tr -d "\",")
if [ "$MOST_RECENT_TAG" == "$DOCKER_TAG" ]; then
  docker tag $IMAGE_NAME $DOCKER_REPO:most_recent_tag
  docker push $DOCKER_REPO:most_recent_tag
elif [ "$SOURCE_BRANCH" = "most_recent_tag" ]; then
  docker tag $IMAGE_NAME $DOCKER_REPO:$MOST_RECENT_TAG
  docker push $DOCKER_REPO:$MOST_RECENT_TAG
elif [ "$SOURCE_BRANCH" = "master" ]; then
  MASTER_COMMIT_SHA=$(curl -s https://api.github.com/repos/lightningnetwork/lnd/branches/master  | grep -i sha | awk 'NR==1{print $2}' | tr -d "\",")
  docker tag $IMAGE_NAME $DOCKER_REPO:"$MASTER_COMMIT_SHA"
  docker push $DOCKER_REPO:"$MASTER_COMMIT_SHA"
fi
